name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t nextwas/react-test -f 3.fibonacci-sequence/client/Dockerfile.dev 3.fibonacci-sequence/client
      - run: docker run -e CI=true nextwas/react-test npm test
 
      - run: docker build -t nextwas/multi-client-10-14 3.fibonacci-sequence/client
      - run: docker build -t nextwas/multi-nginx-10-14 3.fibonacci-sequence/nginx
      - run: docker build -t nextwas/multi-server-10-14 3.fibonacci-sequence/server
      - run: docker build -t nextwas/multi-worker-10-14 3.fibonacci-sequence/worker
 
      - run: docker push nextwas/multi-client-10-14
      - run: docker push nextwas/multi-nginx-10-14
      - run: docker push nextwas/multi-server-10-14
      - run: docker push nextwas/multi-worker-10-14

      - name: Generate deployment package
        run: cd ./3.fibonacci-sequence && 
             zip -r deploy.zip . -x '*.git*'
     
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
            application_name: multi-deployment
            environment_name: Multideployment-env
            existing_bucket_name: elasticbeanstalk-us-east-1-528304107701
            region: us-east-1
            version_label: ${{ github.sha }}
            deployment_package: ./3.fibonacci-sequence/deploy.zip