    name: Deploy Frontend
    on:
      push:
        branches:
          - main # check your repo, your default branch might be master!
     
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          - run:
              cd 2.production-grade-workflow/frontend  &&
              docker build -t nextwas/react-test -f Dockerfile.dev .
          - run: docker run -e CI=true nextwas/react-test npm test
     
          - name: Generate deployment package
            run: 
              cd ./2.production-grade-workflow/frontend && 
              zip -r deploy.zip . -x '*.git*'
     
          - name: Deploy to EB
            uses: einaregilsson/beanstalk-deploy@v18
            with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
              aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
              application_name: docker-react
              environment_name: Dockerreact-env1
              existing_bucket_name: elasticbeanstalk-us-east-1-528304107701
              region: us-east-1
              version_label: ${{ github.sha }}
              deployment_package: ./2.production-grade-workflow/frontend/deploy.zip


